name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    # container: node:13.5.0-alpine3.10
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:300
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/users -H 'Content-Type: application/json' -d '{\"username\": \"hello\", \"address\": \"asdsad\"}'"
      - name: Get Users
        run: curl http://localhost:3001/api/users
