name: "Shell Commands"
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
        # timeout-minutes: 360 - max amount of minutes that the process can long
        # continue-on-error: true - continue with the other steps even if the past has failed
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: "python Commands"
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-bash-window:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
